/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.baldaccini.bkpsgbweb.swing;

import javax.swing.JFileChooser;

/**
 *
 * @author baldaccini
 */
public class LocalSalvar extends javax.swing.JFrame {

    private final ConfigBkp configBkp;
    private DestinoFtp dFtp;
    private Thread th;

    /**
     * Creates new form LocalSalvar
     *
     * @param configBkp
     */
    public LocalSalvar(ConfigBkp configBkp) {
        initComponents();
        this.pnlArqFtp.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.configBkp = configBkp;
        this.setIconImage(new Icone().Icone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlArqEscLocalSalvar = new javax.swing.JPanel();
        radArqDestino = new javax.swing.JRadioButton();
        radArqFtp = new javax.swing.JRadioButton();
        pnlArqLocalSalvar = new javax.swing.JPanel();
        pnlArqDestino = new javax.swing.JPanel();
        btnArqDestino = new javax.swing.JButton();
        txtArqDestino = new javax.swing.JTextField();
        lblArqDestino = new javax.swing.JLabel();
        pnlArqFtp = new javax.swing.JPanel();
        lblArqIp = new javax.swing.JLabel();
        txtArqIp = new javax.swing.JTextField();
        lblArqPorta = new javax.swing.JLabel();
        txtArqPorta = new javax.swing.JTextField();
        lblArqUsuario = new javax.swing.JLabel();
        txtArqUsuario = new javax.swing.JTextField();
        lblArqSenha = new javax.swing.JLabel();
        pasArqSenha = new javax.swing.JPasswordField();
        btnArqConectar = new javax.swing.JButton();
        chkModoPassivo = new javax.swing.JCheckBox();
        lblArqDiretorio = new javax.swing.JLabel();
        txtArqDiretorio = new javax.swing.JTextField();
        btnArqPronto = new javax.swing.JButton();
        lblArqNotificacoesLocalSalvar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Local Salvar");

        pnlArqEscLocalSalvar.setBorder(javax.swing.BorderFactory.createTitledBorder("Local Salvar"));

        buttonGroup1.add(radArqDestino);
        radArqDestino.setSelected(true);
        radArqDestino.setText("Destino");
        radArqDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radArqDestinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radArqFtp);
        radArqFtp.setText("FTP");
        radArqFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radArqFtpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArqEscLocalSalvarLayout = new javax.swing.GroupLayout(pnlArqEscLocalSalvar);
        pnlArqEscLocalSalvar.setLayout(pnlArqEscLocalSalvarLayout);
        pnlArqEscLocalSalvarLayout.setHorizontalGroup(
            pnlArqEscLocalSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArqEscLocalSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radArqDestino)
                .addGap(18, 18, 18)
                .addComponent(radArqFtp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArqEscLocalSalvarLayout.setVerticalGroup(
            pnlArqEscLocalSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArqEscLocalSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArqEscLocalSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radArqDestino)
                    .addComponent(radArqFtp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlArqLocalSalvar.setBorder(javax.swing.BorderFactory.createTitledBorder("Salvar"));

        btnArqDestino.setBackground(new java.awt.Color(0, 51, 153));
        btnArqDestino.setForeground(java.awt.Color.white);
        btnArqDestino.setText("Destino");
        btnArqDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqDestinoActionPerformed(evt);
            }
        });

        txtArqDestino.setBackground(new java.awt.Color(204, 204, 204));

        lblArqDestino.setText("Destino:");

        javax.swing.GroupLayout pnlArqDestinoLayout = new javax.swing.GroupLayout(pnlArqDestino);
        pnlArqDestino.setLayout(pnlArqDestinoLayout);
        pnlArqDestinoLayout.setHorizontalGroup(
            pnlArqDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArqDestinoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblArqDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArqDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArqDestino)
                .addContainerGap())
        );
        pnlArqDestinoLayout.setVerticalGroup(
            pnlArqDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArqDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArqDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArqDestinoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtArqDestino))
                    .addGroup(pnlArqDestinoLayout.createSequentialGroup()
                        .addGroup(pnlArqDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArqDestino)
                            .addComponent(btnArqDestino))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblArqIp.setText("IP:");

        txtArqIp.setBackground(new java.awt.Color(204, 204, 204));
        txtArqIp.setText("192.168.0.104");

        lblArqPorta.setText("Porta:");

        txtArqPorta.setBackground(new java.awt.Color(204, 204, 204));

        lblArqUsuario.setText("Usuario:");

        txtArqUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtArqUsuario.setText("debian");

        lblArqSenha.setText("Senha:");

        pasArqSenha.setBackground(new java.awt.Color(204, 204, 204));
        pasArqSenha.setText("debian");

        btnArqConectar.setBackground(new java.awt.Color(0, 51, 153));
        btnArqConectar.setForeground(java.awt.Color.white);
        btnArqConectar.setText("Conectar");
        btnArqConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqConectarActionPerformed(evt);
            }
        });

        chkModoPassivo.setText("Modo passivo");

        lblArqDiretorio.setText("Diretório:");

        javax.swing.GroupLayout pnlArqFtpLayout = new javax.swing.GroupLayout(pnlArqFtp);
        pnlArqFtp.setLayout(pnlArqFtpLayout);
        pnlArqFtpLayout.setHorizontalGroup(
            pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArqFtpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlArqFtpLayout.createSequentialGroup()
                            .addComponent(btnArqConectar)
                            .addGap(18, 18, 18)
                            .addComponent(chkModoPassivo)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(pnlArqFtpLayout.createSequentialGroup()
                            .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblArqUsuario)
                                .addComponent(lblArqSenha)
                                .addComponent(lblArqDiretorio))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtArqUsuario)
                                .addComponent(pasArqSenha)
                                .addComponent(txtArqIp)
                                .addComponent(txtArqDiretorio))))
                    .addComponent(lblArqIp))
                .addGap(6, 6, 6)
                .addComponent(lblArqPorta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArqPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlArqFtpLayout.setVerticalGroup(
            pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArqFtpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArqIp)
                    .addComponent(txtArqIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArqPorta)
                    .addComponent(txtArqPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArqUsuario)
                    .addComponent(txtArqUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArqSenha)
                    .addComponent(pasArqSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArqDiretorio)
                    .addComponent(txtArqDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlArqFtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArqConectar)
                    .addComponent(chkModoPassivo))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlArqLocalSalvarLayout = new javax.swing.GroupLayout(pnlArqLocalSalvar);
        pnlArqLocalSalvar.setLayout(pnlArqLocalSalvarLayout);
        pnlArqLocalSalvarLayout.setHorizontalGroup(
            pnlArqLocalSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlArqDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlArqFtp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlArqLocalSalvarLayout.setVerticalGroup(
            pnlArqLocalSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArqLocalSalvarLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(pnlArqDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlArqFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnArqPronto.setBackground(new java.awt.Color(0, 51, 153));
        btnArqPronto.setForeground(java.awt.Color.white);
        btnArqPronto.setText("Pronto");
        btnArqPronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqProntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlArqEscLocalSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlArqLocalSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArqNotificacoesLocalSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnArqPronto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlArqEscLocalSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(pnlArqLocalSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArqNotificacoesLocalSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArqPronto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArqDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqDestinoActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(fc) == JFileChooser.APPROVE_OPTION) {
            txtArqDestino.setText(fc.getSelectedFile().getPath() + "/");
            configBkp.setDestino(fc.getSelectedFile().getPath() + "/");
        } else {
            txtArqDestino.setText("");
            configBkp.setDestino("");
        }
    }//GEN-LAST:event_btnArqDestinoActionPerformed

    private void radArqDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radArqDestinoActionPerformed
        pnlArqDestino.setVisible(true);
        pnlArqFtp.setVisible(false);
    }//GEN-LAST:event_radArqDestinoActionPerformed

    private void radArqFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radArqFtpActionPerformed
        pnlArqDestino.setVisible(false);
        pnlArqFtp.setVisible(true);
    }//GEN-LAST:event_radArqFtpActionPerformed

    private void btnArqProntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqProntoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnArqProntoActionPerformed

    private void btnArqConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqConectarActionPerformed
        dFtp = new DestinoFtp(this.configBkp);
        if (null != btnArqConectar.getText()) {
            switch (btnArqConectar.getText()) {
                case "Conectar":
                    Runnable rn = new Runnable() {

                        @Override
                        public void run() {
                            if (!"".equals(txtArqIp.getText())) {
                                lblArqNotificacoesLocalSalvar.setText("Conectando...");
                                btnArqConectar.setText("Cancelar");
                                if (dFtp.getFtpExterno().conectar(txtArqIp.getText(), "".equals(txtArqPorta.getText()) ? 21 : Integer.parseInt(txtArqPorta.getText()), txtArqUsuario.getText(), String.valueOf(pasArqSenha.getPassword()), txtArqDiretorio.getText(), chkModoPassivo.isSelected())) {
                                    btnArqConectar.setText("Desconectar");
                                    lblArqNotificacoesLocalSalvar.setText("Conectado!");
                                    configBkp.setFtpIp(txtArqIp.getText());
                                    configBkp.setFtpPorta(txtArqPorta.getText());
                                    configBkp.setFtpLogin(txtArqUsuario.getText());
                                    configBkp.setFtpSenha(pasArqSenha.getPassword().toString());
                                    configBkp.setFtpModoConexao(String.valueOf(chkModoPassivo.isSelected()));
                                    dFtp.setVisible(true);
                                } else {
                                    btnArqConectar.setText("Conectar");
                                    lblArqNotificacoesLocalSalvar.setText("Erro ao conectar!");
                                }
                            }
                        }
                    };
                    th = new Thread(rn);
                    th.setName("ConectarFtp");
                    th.start();
                    break;
                case "Desconectar":
                    if (dFtp.getFtpExterno().desconectar()) {
                        btnArqConectar.setText("Conectar");
                        lblArqNotificacoesLocalSalvar.setText("Desconectado");
                        dFtp.getFtpExterno().fecharJanela();
                    } else {
                        dFtp.getFtpExterno().fecharJanela();
                        dFtp = null;
                        btnArqConectar.setText("Conectar");
                        lblArqNotificacoesLocalSalvar.setText("Desconectado");
                    }
                    break;
                case "Cancelar":
                    if (dFtp.getFtpExterno().desconectar()) {
                        btnArqConectar.setText("Conectar");
                        lblArqNotificacoesLocalSalvar.setText("Cancelado");
                    } else {
                        dFtp = null;
                        btnArqConectar.setText("Conectar");
                        lblArqNotificacoesLocalSalvar.setText("Desconectado");
                        dFtp.getFtpExterno().fecharJanela();
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnArqConectarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArqConectar;
    private javax.swing.JButton btnArqDestino;
    private javax.swing.JButton btnArqPronto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkModoPassivo;
    private javax.swing.JLabel lblArqDestino;
    private javax.swing.JLabel lblArqDiretorio;
    private javax.swing.JLabel lblArqIp;
    private javax.swing.JLabel lblArqNotificacoesLocalSalvar;
    private javax.swing.JLabel lblArqPorta;
    private javax.swing.JLabel lblArqSenha;
    private javax.swing.JLabel lblArqUsuario;
    private javax.swing.JPasswordField pasArqSenha;
    private javax.swing.JPanel pnlArqDestino;
    private javax.swing.JPanel pnlArqEscLocalSalvar;
    private javax.swing.JPanel pnlArqFtp;
    private javax.swing.JPanel pnlArqLocalSalvar;
    private javax.swing.JRadioButton radArqDestino;
    private javax.swing.JRadioButton radArqFtp;
    private javax.swing.JTextField txtArqDestino;
    private javax.swing.JTextField txtArqDiretorio;
    private javax.swing.JTextField txtArqIp;
    private javax.swing.JTextField txtArqPorta;
    private javax.swing.JTextField txtArqUsuario;
    // End of variables declaration//GEN-END:variables
}
