/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.baldaccini.bkpsgbweb.swing;

/**
 *
 * @author ETEC
 */
public class LocalWeb extends javax.swing.JFrame {

    /**
     * Creates new form LocalWeb
     */
    public LocalWeb() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new Icone().Icone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_local = new javax.swing.JButton();
        btn_web = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Local ou Web");

        btn_local.setBackground(new java.awt.Color(0, 51, 153));
        btn_local.setForeground(new java.awt.Color(255, 255, 255));
        btn_local.setText("LOCAL");
        btn_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_localActionPerformed(evt);
            }
        });

        btn_web.setBackground(new java.awt.Color(0, 51, 153));
        btn_web.setForeground(new java.awt.Color(255, 255, 255));
        btn_web.setText("WEB");
        btn_web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_webActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_local, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_web, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_web, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(btn_local, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_localActionPerformed
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_localActionPerformed

    private void btn_webActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_webActionPerformed
        new LoginWeb().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_webActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_local;
    private javax.swing.JButton btn_web;
    // End of variables declaration//GEN-END:variables
}
