/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.baldaccini.bkpsgbweb.swing;

import java.io.IOException;
import java.net.SocketException;
import javax.swing.JOptionPane;
import org.apache.commons.net.ftp.FTPClient;

/**
 *
 * @author ETEC
 */
public class LoginWeb extends javax.swing.JFrame {
    
    public FTPClient ftp = new FTPClient();

    /**
     * Creates new form LoginWeb
     */
    public LoginWeb() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new Icone().Icone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_servidor = new javax.swing.JLabel();
        txt_servidor = new javax.swing.JTextField();
        lbl_login = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        pass_senha = new javax.swing.JPasswordField();
        lbl_senha = new javax.swing.JLabel();
        btn_conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conectar ao servidor");

        lbl_servidor.setText("Servidor");

        txt_servidor.setBackground(new java.awt.Color(204, 204, 204));
        txt_servidor.setText("ftp.tecprisma.com.br");
        txt_servidor.setPreferredSize(new java.awt.Dimension(52, 20));

        lbl_login.setText("Login");

        txt_login.setBackground(new java.awt.Color(204, 204, 204));
        txt_login.setText("tecprisma");

        pass_senha.setBackground(new java.awt.Color(204, 204, 204));
        pass_senha.setText("tec2013");

        lbl_senha.setText("Senha");

        btn_conectar.setBackground(new java.awt.Color(0, 51, 153));
        btn_conectar.setForeground(new java.awt.Color(255, 255, 255));
        btn_conectar.setText("Conectar");
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_login)
                            .addComponent(lbl_senha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_login)
                            .addComponent(pass_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_conectar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_servidor)
                        .addGap(8, 8, 8)
                        .addComponent(txt_servidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_servidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_login)
                    .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senha)
                    .addComponent(pass_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        try {
            this.ftp.connect(txt_servidor.getText());
        } catch (SocketException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        try {
            if (this.ftp.login(txt_login.getText(), String.valueOf(pass_senha.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Conectado!!");
                new Principal().setVisible(true);
                this.setVisible(false);
            } else {
                this.ftp.disconnect();
                this.ftp = null;
                JOptionPane.showMessageDialog(null, "Falha de autenticação!");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_conectarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conectar;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_servidor;
    private javax.swing.JPasswordField pass_senha;
    private javax.swing.JTextField txt_login;
    private javax.swing.JTextField txt_servidor;
    // End of variables declaration//GEN-END:variables
}
