/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.baldaccini.bkpsgbweb.swing;

import br.com.baldaccini.bkpsgbweb.log.GravarArquivoLog;
import java.io.FileNotFoundException;
import br.com.baldaccini.bkpsgbweb.redefinirsenha.RedefinirSenhaEmail;
import java.io.IOException;
import javax.swing.JOptionPane;
import br.com.baldaccini.bkpsgbweb.util.Criptografia;
import br.com.baldaccini.bkpsgbweb.xml.LoginXML;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdom2.JDOMException;

/**
 *
 * @author Rosemary
 */
public class RedefinirSenhaLocal extends javax.swing.JFrame {

    /**
     * Creates new form RedefinirSenhaLocal
     */
    public RedefinirSenhaLocal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new Icone().Icone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_senhaAtual = new javax.swing.JLabel();
        lbl_novaSenha = new javax.swing.JLabel();
        lbl_confNovaSenha = new javax.swing.JLabel();
        passSenhaAtual = new javax.swing.JPasswordField();
        passNovaSenha = new javax.swing.JPasswordField();
        passConfNovaSenha = new javax.swing.JPasswordField();
        btnAlterarSenha = new javax.swing.JButton();
        btnEnviarSenhaEmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Redefinir Senha");

        lbl_senhaAtual.setText("Senha atual:");

        lbl_novaSenha.setText("Nova senha:");

        lbl_confNovaSenha.setText("Confirmar nova senha:");

        passSenhaAtual.setBackground(new java.awt.Color(204, 204, 204));

        passNovaSenha.setBackground(new java.awt.Color(204, 204, 204));

        passConfNovaSenha.setBackground(new java.awt.Color(204, 204, 204));

        btnAlterarSenha.setBackground(new java.awt.Color(0, 51, 153));
        btnAlterarSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarSenha.setText("Alterar senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        btnEnviarSenhaEmail.setBackground(new java.awt.Color(0, 51, 153));
        btnEnviarSenhaEmail.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarSenhaEmail.setText("Enviar senha por e-mail");
        btnEnviarSenhaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSenhaEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_novaSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviarSenhaEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_senhaAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_confNovaSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passConfNovaSenha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_senhaAtual))
                    .addComponent(passSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_novaSenha))
                    .addComponent(passNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_confNovaSenha)
                    .addComponent(passConfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarSenhaEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        if ((!String.valueOf(passSenhaAtual.getPassword()).equals("") && !String.valueOf(passConfNovaSenha.getPassword()).equals("")) && String.valueOf(passNovaSenha.getPassword()).equals(String.valueOf(passConfNovaSenha.getPassword()))) {
            LoginXML loginXML = new LoginXML();
            if (loginXML.lerLogin().getPass().equals(Criptografia.encrypt(String.valueOf(passSenhaAtual.getPassword())))) {
                try {
                    if (!String.valueOf(passSenhaAtual.getPassword()).equals(String.valueOf(passNovaSenha.getPassword()))) {
                        if (loginXML.alterar(Criptografia.encrypt(String.valueOf(passNovaSenha.getPassword())))) {
                            JOptionPane.showMessageDialog(null, "Senha alterada com sucesso!");
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Senha não pode ser alterada.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Não é possivel alterar usando a senha atual!");
                    }
                } catch (FileNotFoundException ex) {
                    GravarArquivoLog.gravarTodosLog(ex.getMessage());
                } catch (IOException ex) {
                    GravarArquivoLog.gravarTodosLog(ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Senha atual incorreta!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Confirmação de senha está incorreta.");
        }
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void btnEnviarSenhaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSenhaEmailActionPerformed
        try {
            new RedefinirSenhaEmail().dadosEmail();
        } catch (JDOMException | IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnEnviarSenhaEmailActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnEnviarSenhaEmail;
    private javax.swing.JLabel lbl_confNovaSenha;
    private javax.swing.JLabel lbl_novaSenha;
    private javax.swing.JLabel lbl_senhaAtual;
    private javax.swing.JPasswordField passConfNovaSenha;
    private javax.swing.JPasswordField passNovaSenha;
    private javax.swing.JPasswordField passSenhaAtual;
    // End of variables declaration//GEN-END:variables
}
