/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.baldaccini.bkpsgbweb.relatorio;

import br.com.baldaccini.bkpsgbweb.swing.Icone;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author jhone
 */
public class RelatorioFrame extends javax.swing.JFrame {
    
    private RelatorioArquivo ra;

    /**
     * Creates new form RelatorioFrameArquivo
     */
    public RelatorioFrame() {
        initComponents();
        this.setIconImage(new Icone().Icone());
        this.setLocationRelativeTo(null);
        ra = new RelatorioArquivo();
        carregarArquivosRelatorio();
    }

    private void carregarArquivosRelatorio() {
        DefaultListModel listaModelo = new DefaultListModel();
        File file = new File("relatorio");
        if (!file.exists()) {
            file.mkdir();
        }
        for (File f : file.listFiles()) {
            listaModelo.addElement(f.getName());
        }
        lstBackupArquivo.setModel(listaModelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpRelatorioArquivo = new javax.swing.JTabbedPane();
        pnlRelatorioArquivo = new javax.swing.JPanel();
        btnGerarRelatorio = new javax.swing.JButton();
        btnSalvarComo = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstBackupArquivo = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaRelatorioArquivo = new javax.swing.JTextArea();
        pnlRelatorioBancoDados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edpRelatorioBancoDados = new javax.swing.JEditorPane();
        pbBdGerandoRelatorio = new javax.swing.JProgressBar();
        btnBdGerarRelatorio = new javax.swing.JButton();
        btnBdSalvarComo = new javax.swing.JButton();
        lblBdMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório");

        btnGerarRelatorio.setBackground(new java.awt.Color(0, 51, 153));
        btnGerarRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarRelatorio.setText("Gerar Relatorio");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        btnSalvarComo.setBackground(new java.awt.Color(0, 51, 153));
        btnSalvarComo.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarComo.setText("Salvar como...");
        btnSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarComoActionPerformed(evt);
            }
        });

        lstBackupArquivo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstBackupArquivo);

        txaRelatorioArquivo.setEditable(false);
        txaRelatorioArquivo.setColumns(20);
        txaRelatorioArquivo.setLineWrap(true);
        txaRelatorioArquivo.setRows(5);
        txaRelatorioArquivo.setWrapStyleWord(true);
        txaRelatorioArquivo.setCaretPosition(txaRelatorioArquivo.getDocument().getLength());
        jScrollPane4.setViewportView(txaRelatorioArquivo);
        ((DefaultCaret) txaRelatorioArquivo.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        javax.swing.GroupLayout pnlRelatorioArquivoLayout = new javax.swing.GroupLayout(pnlRelatorioArquivo);
        pnlRelatorioArquivo.setLayout(pnlRelatorioArquivoLayout);
        pnlRelatorioArquivoLayout.setHorizontalGroup(
            pnlRelatorioArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioArquivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelatorioArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(pnlRelatorioArquivoLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRelatorioArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRelatorioArquivoLayout.createSequentialGroup()
                        .addComponent(btnSalvarComo)
                        .addGap(18, 18, 18)
                        .addComponent(btnGerarRelatorio)))
                .addContainerGap())
        );
        pnlRelatorioArquivoLayout.setVerticalGroup(
            pnlRelatorioArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioArquivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelatorioArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRelatorioArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRelatorioArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSalvarComo)
                        .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );

        tpRelatorioArquivo.addTab("Relatorio Arquivo", pnlRelatorioArquivo);

        jScrollPane1.setViewportView(edpRelatorioBancoDados);

        btnBdGerarRelatorio.setBackground(new java.awt.Color(0, 51, 153));
        btnBdGerarRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnBdGerarRelatorio.setText("Gerar Relatorio");

        btnBdSalvarComo.setBackground(new java.awt.Color(0, 51, 153));
        btnBdSalvarComo.setForeground(new java.awt.Color(255, 255, 255));
        btnBdSalvarComo.setText("Salvar como...");

        javax.swing.GroupLayout pnlRelatorioBancoDadosLayout = new javax.swing.GroupLayout(pnlRelatorioBancoDados);
        pnlRelatorioBancoDados.setLayout(pnlRelatorioBancoDadosLayout);
        pnlRelatorioBancoDadosLayout.setHorizontalGroup(
            pnlRelatorioBancoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioBancoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelatorioBancoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(pbBdGerandoRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRelatorioBancoDadosLayout.createSequentialGroup()
                        .addComponent(lblBdMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                        .addComponent(btnBdSalvarComo)
                        .addGap(18, 18, 18)
                        .addComponent(btnBdGerarRelatorio)))
                .addContainerGap())
        );
        pnlRelatorioBancoDadosLayout.setVerticalGroup(
            pnlRelatorioBancoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioBancoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRelatorioBancoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRelatorioBancoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBdSalvarComo)
                        .addComponent(btnBdGerarRelatorio))
                    .addComponent(lblBdMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbBdGerandoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpRelatorioArquivo.addTab("Relatorio Bando de Dados", pnlRelatorioBancoDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpRelatorioArquivo, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpRelatorioArquivo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        Runnable rn = new Runnable() {
            @Override
            public void run() {
                if (lstBackupArquivo.getModel().getSize() > 0) {
                    if (lstBackupArquivo.getSelectedIndex() >= 0) {
                        lblMensagem.setText("Gerando Relatório...");
                        txaRelatorioArquivo.setText("");
                        txaRelatorioArquivo.setText(ra.carregarRelatorioArquivo(lstBackupArquivo.getSelectedValue().toString()).toString());
                        lblMensagem.setText("Relatório gerado com sucesso!");
                    } else {
                        lblMensagem.setText("Selecione um backup na lista!");
                    }
                } else {
                    lblMensagem.setText("Não existe arquivos de relatório. Aguarde até que o primeiro backup seja feito!");
                }
            }
        };
        Thread th = new Thread(rn);
        th.setName("GerandoRelatorioArquivo");
        th.start();

    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void btnSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarComoActionPerformed
        ra.gravarRelatorio("nome", "databkpagendado", "local", "destino", 100l, "diaHora");
    }//GEN-LAST:event_btnSalvarComoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RelatorioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBdGerarRelatorio;
    private javax.swing.JButton btnBdSalvarComo;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnSalvarComo;
    private javax.swing.JEditorPane edpRelatorioBancoDados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBdMensagem;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JList lstBackupArquivo;
    private javax.swing.JProgressBar pbBdGerandoRelatorio;
    private javax.swing.JPanel pnlRelatorioArquivo;
    private javax.swing.JPanel pnlRelatorioBancoDados;
    private javax.swing.JTabbedPane tpRelatorioArquivo;
    private javax.swing.JTextArea txaRelatorioArquivo;
    // End of variables declaration//GEN-END:variables
}
